### ISSUE TITLE
请问有没有产生embedding的代码，我好像没有找到

### ISSUE THREAD

**Issue by swordqiqi** [ljy0ustc/LLaRA#11]

**Comment by swordqiqi** [comment]
就是使用协同过滤模型产生embedding的代码，您是如何写的呢？

**Comment by ljy0ustc** [comment]
Thanks for your attention to our work. Please see the reply in another issuse [https://github.com/ljy0ustc/LLaRA/issues/14#issuecomment-2209231684](url).
