### ISSUE TITLE
请问SASRec、GRURec、Caser这些对比模型是怎么训练的

### ISSUE THREAD

**Issue by nanchuan-max** [ljy0ustc/LLaRA#12]
作者你好！这篇文章思路挺不错的，我已经复现了该模型，想看看对比实验是怎么做的，看源码写了这些模型的定义和forward函数，想知道后面的训练过程是怎么样的，用的什么数据，什么损失函数，怎么去评估的

**Comment by ljy0ustc** [comment]
Thanks for your attention to our work. Please see the reply in another issue [https://github.com/ljy0ustc/LLaRA/issues/14#issuecomment-2209231684](url)
