### ISSUE TITLE
Inquiring about the rec_model for running on other datasets.

### ISSUE THREAD

**Issue by weiwei-du** [ljy0ustc/LLaRA#14]
Dear Authors,

Thank you for sharing the code, checkpoints and datasets.
Could I inquire about how to generate the rec_model if I would like to run the code on datasets other than MovieLens, Steam, and FastFM?
Thank you and look forward to your reply.

Regards,
Wei-Wei

**Comment by ljy0ustc** [comment]
Thanks for your attention to our work. The code for generating the rec_model is adapted from the repo https://github.com/YangZhengyi98/DROS.
