### ISSUE TITLE
代码似乎不是从易到难而是从难到易开始训练的？（>号<号似乎写反了？）

### ISSUE THREAD

**Issue by mfj12315** [ljy0ustc/LLaRA#15]
代码似乎不是从易到难而是从难到易开始训练的？（>号<号似乎写反了？）,在[LLaRA](https://github.com/ljy0ustc/LLaRA/tree/main)/[data](https://github.com/ljy0ustc/LLaRA/tree/main/data)
/data_interface.py中，如果随机数p>阈值则使用混合的难度更大的prompt，但是阈值随着训练的step增大而增大，因此实际训练时训练任务在一开始最难，后面越来越简单，详细见下图

![123](https://github.com/ljy0ustc/LLaRA/assets/150609095/d3c5a20a-2c98-4e57-a105-5129e836dd0b)

**Comment by ljy0ustc** [comment]
Thanks for your attention to our work. Please see the English version of this issue.
