### ISSUE TITLE
tensor shape mismatch

### ISSUE THREAD

**Issue by aivolcano** [ljy0ustc/LLaRA#6]
The Tensor shape of targets variable mismatch in line 32 (model_inference.py)

 targets = targets.masked_fill((batch["tokens"].token_type_ids == 0)[:,1:], -100)
RuntimeError: The size of tensor a (220) must match the size of tensor b (221) at non-singleton dimension 1

Below is the source code 
 def forward(self, batch):
        targets = batch["tokens"].input_ids.masked_fill(
            batch["tokens"].input_ids == self.llama_tokenizer.pad_token_id, -100
        ) # [batch_size, max_len]
        targets = targets.masked_fill((batch["tokens"].token_type_ids == 0)[:,1:], -100)
        input_embeds = self.wrap_emb(batch)
        outputs = self.llama_model(
            inputs_embeds=input_embeds,
            attention_mask=batch["tokens"].attention_mask,
            return_dict=True,
            labels=targets,
            use_cache=False
        )
        return outputs

**Comment by Fa1con-Hsui** [comment]
@aivolcano hey bro, we have met with this problem too, can you tell us how did you solve this issue?

**Comment by JinsongLiu6** [comment]
@aivolcano @Fa1con-Hsui @ljy0ustc 
Hi, I met the same issue, how can I resolve it?
Thanks for your help!
